export const appHtml = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>172X Data Intelligence</title>
<style>
:root{font-family:Inter,ui-sans-serif,system-ui,sans-serif;color:#10202d;background:#eef4f7}
*{box-sizing:border-box}body{margin:0;min-height:100vh;background:radial-gradient(circle at 15% 0,#d9f6ee,transparent 42%),#eef4f7}
main{width:min(960px,calc(100% - 32px));margin:0 auto;padding:48px 0 72px}header{display:flex;justify-content:space-between;gap:24px;align-items:end;margin-bottom:28px}
h1{font-size:clamp(2rem,5vw,4rem);letter-spacing:-.06em;line-height:.95;margin:0;max-width:620px}p{line-height:1.55;color:#49616e}.eyebrow{color:#047c68;font-weight:800;letter-spacing:.12em;text-transform:uppercase;font-size:.75rem}
.card{background:#fff;border:1px solid #d4e2e8;border-radius:22px;padding:22px;box-shadow:0 18px 50px #173b4d12;margin-top:16px}.card h2{margin:0;font-size:1.35rem}.sources{display:flex;gap:10px;flex-wrap:wrap}.source,.suggestion,button{border:1px solid #bfd1d9;background:#fff;border-radius:999px;padding:10px 15px;font:inherit;cursor:pointer;color:#17313d}.source.active{background:#123e4b;color:#fff;border-color:#123e4b}.suggestions{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.suggestion{font-size:.9rem;background:#f5fafb}
textarea{width:100%;min-height:112px;resize:vertical;border:1px solid #b8ccd5;border-radius:14px;padding:14px;font:inherit;color:inherit;margin-top:8px}button.primary{background:#e86f4f;color:#fff;border-color:#e86f4f;font-weight:700}button:disabled{opacity:.45;cursor:not-allowed}.actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap;margin-top:12px}.status{min-height:24px;color:#49616e;font-size:.92rem}.answer{font-size:1.15rem;white-space:pre-wrap;color:#163541}.answer strong{font-size:1.35rem}.notice{border-left:4px solid #e86f4f;padding-left:12px}.meta{font-size:.84rem;color:#607985}.citations{display:grid;gap:10px;margin-top:12px}.citation{background:#f5fafb;border-radius:12px;padding:12px}.citation b{color:#047c68}.citation q{display:block;margin-top:5px;color:#294c59}.empty{color:#6b808a}.topline{display:flex;justify-content:space-between;gap:12px;align-items:center}details{margin-top:16px}summary{cursor:pointer;font-weight:700}pre{max-height:300px;overflow:auto;background:#10202d;color:#d8edf0;border-radius:12px;padding:14px;font-size:.75rem;white-space:pre-wrap;word-break:break-word}
@media(max-width:640px){main{padding-top:28px}header{display:block}.card{padding:17px;border-radius:17px}.topline{display:block}.topline .meta{display:block;margin-top:5px}}
</style>
</head>
<body><main>
<header><div><div class="eyebrow">172X / synthetic data lab</div><h1>Ask your data a better question.</h1><p>Read-only analysis grounded in bundled sales and support fixtures. Every answer shows its evidence and limits.</p></div><div class="meta">Cloudflare Workers AI · Llama 3.3</div></header>
<section class="card"><div class="topline"><h2>Choose a source</h2><span id="sourceHelp" class="meta"></span></div><div class="sources"><button class="source" data-source="sales">Sales demo</button><button class="source" data-source="support">Support messages</button></div><div id="suggestions" class="suggestions"></div></section>
<section class="card"><label for="question"><b>Your question</b></label><textarea id="question" maxlength="1024" placeholder="Try: What are total net units?"></textarea><div class="actions"><button id="ask" class="primary">Ask 172X</button><button id="cancel">Cancel</button><button id="reset">New session</button><span id="status" class="status" aria-live="polite"></span></div></section>
<section class="card"><div class="topline"><h2>Answer</h2><span id="answerMeta" class="meta"></span></div><div id="answer" class="answer empty">Select a source and ask a question.</div><div id="citations" class="citations"></div><details><summary>Inspect evidence</summary><pre id="evidence">No evidence yet.</pre></details></section>
</main>
<script>
const sources={sales:{version:'1',source_id:'sales',snapshot_sha256:'a55c2b2a8a9378830e8e8dd13e7df1dcf9de6d87ce39f13f97aa4c48ed7ca84f',meaning_revision:'sales-demo.v1'},support:{version:'1',source_id:'support',snapshot_sha256:'c6365aa74909b4deb09bb00114f7b489dcc8c9c152c57855db95fd6304e1e536',meaning_revision:'support-demo.v1'}};
const examples={sales:['What are total net units?','Show total revenue in USD cents','Which regions have the most units?'],support:['Find messages about export errors','Find billing messages from Acme','Search for login trouble']};
let selected='sales', polling=false, requestId=null;
const $=id=>document.getElementById(id), sourceButtons=[...document.querySelectorAll('.source')];
function sourceLabel(){return selected==='sales'?'Sales: totals, groups, rankings and comparisons.':'Support: targeted message search with exact quotes; hits do not establish prevalence.';}
function drawSuggestions(){ $('sourceHelp').textContent=sourceLabel(); $('suggestions').replaceChildren(...examples[selected].map(text=>{const button=document.createElement('button');button.className='suggestion';button.textContent=text;button.onclick=()=>{$('question').value=text;$('question').focus()};return button;})); sourceButtons.forEach(button=>button.classList.toggle('active',button.dataset.source===selected)); }
async function api(path, options={}){const response=await fetch(path,{credentials:'same-origin',...options,headers:{'content-type':'application/json',...(options.headers||{})}});const value=await response.json().catch(()=>({code:'invalid_response'}));if(!response.ok)throw new Error(value.code||'request_failed');return value;}
function phaseText(state){const phase=state.active_job?.phase;if(!phase)return '';return {queued:'Queued…',profiling:'Profiling the source…',planning:'Planning the question…',executing:'Running a bounded query…',validating:'Checking the answer…',awaiting_clarification:'A clarification is needed.',completed:'Complete.',failed:'The request failed.',interrupted:'The request was interrupted.',cancelled:'Cancelled.',budget_exhausted:'The free model-call budget is exhausted.'}[phase]||'Working…';}
function draw(state){if(state.selected_source)selected=state.selected_source.source_id;drawSuggestions();const publication=state.publication?.result;const planner=state.planner?.result;$('status').textContent=phaseText(state);$('ask').disabled=polling||!state.selected_source;$('cancel').disabled=!state.active_job||['completed','failed','interrupted','cancelled','awaiting_clarification','budget_exhausted'].includes(state.active_job.phase);$('answerMeta').textContent=state.model_calls_remaining+' model calls remaining';
if(planner?.kind==='clarification'){$('answer').className='answer notice';$('answer').textContent=planner.question;$('citations').replaceChildren();}else if(publication?.kind==='published'){$('answer').className='answer';$('answer').textContent=publication.answer.text;drawCitations(publication.answer.citations);}else if(publication?.kind==='refusal'){$('answer').className='answer notice';$('answer').textContent='This answer was withheld because validation could not establish a grounded result ('+publication.code+').';$('citations').replaceChildren();}else if(state.active_job?.phase==='failed'){$('answer').className='answer notice';$('answer').textContent='The request could not be completed. Try a narrower question.';}else{$('citations').replaceChildren();$('answer').className=state.active_job?'answer':'answer empty';$('answer').textContent=state.active_job?'Working…':'Select a source and ask a question.';}$('evidence').textContent=JSON.stringify({planner:state.planner,publication:state.publication,last_result:state.last_result},null,2);}
function drawCitations(citations){$('citations').replaceChildren(...(citations||[]).map(citation=>{const box=document.createElement('div');box.className='citation';const id=document.createElement('b');id.textContent=citation.message_id;const quote=document.createElement('q');quote.textContent=citation.quote;box.append(id,quote);return box;}));}
function escapeHtml(value){return value.replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));}
async function refresh(){try{draw(await api('/api/state',{method:'GET'}));}catch(error){$('status').textContent=error.message;}}
async function choose(source){selected=source;drawSuggestions();try{draw(await api('/api/source',{method:'POST',body:JSON.stringify({version:'2',source:sources[source]})}));}catch(error){$('status').textContent=error.message;}}
async function ask(){const question=$('question').value.trim();if(!question||polling)return;polling=true;requestId=crypto.randomUUID();$('answer').textContent='Working…';try{await api('/api/ask',{method:'POST',body:JSON.stringify({version:'2',request_id:requestId,question})});for(let attempt=0;attempt<120;attempt++){const state=await api('/api/state',{method:'GET'});draw(state);if(!state.active_job||['completed','failed','interrupted','cancelled','awaiting_clarification','budget_exhausted'].includes(state.active_job.phase))break;await new Promise(resolve=>setTimeout(resolve,500));}}catch(error){$('status').textContent=error.message;}finally{polling=false;refresh();}}
sourceButtons.forEach(button=>button.onclick=()=>choose(button.dataset.source));$('ask').onclick=ask;$('cancel').onclick=()=>api('/api/cancel',{method:'POST',body:JSON.stringify({version:'2'})}).then(refresh).catch(error=>$('status').textContent=error.message);$('reset').onclick=()=>api('/api/reset',{method:'POST',body:JSON.stringify({version:'2'})}).then(()=>{selected='sales';$('question').value='';$('answer').textContent='Select a source and ask a question.';refresh()}).catch(error=>$('status').textContent=error.message);drawSuggestions();refresh();
</script></body></html>`;
